# fly.toml app configuration file generated for fast-care-backend on 2024-03-11T12:47:22Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fast-care-backend'
primary_region = 'lhr'

[build]

[env]
  DB_DATABASE = "db-fastcare"
  DB_HOST = "54.221.160.166"
  DB_PASSWORD = "19 dec!@#$%"
  DB_PORT = "61199"
  DB_USERNAME = "Adabo"
  GMAIL_PASSWORD = "ikxa rqag ypmc fqna"
  GMAIL_USER = "connect.solutions.ghana00@gmail.com"
  JWT_SECRET = "khjk8gdEDosuvIDcuSS6M0yl71m6a9XboZ1xMNzVXF0"
  MAIL_HOST = "smtp.office365.com"
  MAIL_PASSWORD = "Genesis1:1"
  MAIL_PORT = "587"
  MAIL_USER = "leaveapp@ugmc.ug.edu.gh"
  PORT = "3100"
  SMS_PASSWORD = "19 dec!@#$%"
  SMS_SENDER_ID = "FastCare"
  CUSTOMER_CARE_NO = "03002983847"
  SMS_USERNAME = "adabo"
  PAYMENT_MANDATEKEY = "encsRCb91PWIKd8lfA9aADuKOsXZZWQy"
  PAYMENT_MERCHANTID = "3408"
  PAYMENT_PRODUCTID = "1"
  PAYMENT_URL = "https://ddv15-do.transflowitc.com"

[http_service]
  internal_port = 3100
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
