# fly.toml app configuration file generated for fast-care-backend on 2024-01-23T15:54:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fast-care-backend"
primary_region = "lhr"

[build]

[env]
  DB_DATABASE = "DB_FASTCARE"
  DB_HOST = "mssql-160536-0.cloudclusters.net"
  DB_PASSWORD = "935@Kobby"
  DB_PORT = "18547"
  DB_USERNAME = "cobbs"
  GMAIL_PASSWORD = "ikxa rqag ypmc fqna"
  GMAIL_USER = "connect.solutions.ghana00@gmail.com"
  JWT_SECRET = "khjk8gdEDosuvIDcuSS6M0yl71m6a9XboZ1xMNzVXF0"
  MAIL_HOST = "smtp.office365.com"
  MAIL_PASSWORD = "Genesis1:1"
  MAIL_PORT = "587"
  MAIL_USER = "leaveapp@ugmc.ug.edu.gh"
  PORT = "3100"

[http_service]
  internal_port = 3100
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 2
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
